function [fitresult, gof] = createFit(X1, Y1, smoothingP)
    %CREATEFIT(X1,Y1)
    %  Create a fit.
    %
    %  Data for 'untitled fit 1' fit:
    %      X Input : X1
    %      Y Output: Y1
    %  Output:
    %      fitresult : a fit object representing the fit.
    %      gof : structure with goodness-of fit info.
    %
    %  See also FIT, CFIT, SFIT.
    
    %  Auto-generated by MATLAB on 07-Nov-2017 05:18:34
    
    
    %% Fit: 'untitled fit 1'.
    [xData, yData] = prepareCurveData( X1, Y1 );
    
    % Set up fittype and options.
    ft = fittype( 'smoothingspline' );
    opts = fitoptions( 'Method', 'SmoothingSpline' );
    opts.SmoothingParam = smoothingP;
    
    % Fit model to data.
    [fitresult, gof] = fit( xData, yData, ft, opts );
    plot( fitresult);
