function [fitresult, gof] = createFit(X1, Y1)
    %CREATEFIT(X1,Y1)
    %  Create a fit.
    %
    %  Data for 'untitled fit 1' fit:
    %      X Input : X1
    %      Y Output: Y1
    %  Output:
    %      fitresult : a fit object representing the fit.
    %      gof : structure with goodness-of fit info.
    %
    %  See also FIT, CFIT, SFIT.
    
    %  Auto-generated by MATLAB on 18-Sep-2017 22:38:29
    
    
    %% Fit: 'untitled fit 1'.
    [xData, yData] = prepareCurveData( X1, Y1 );
    
    % Set up fittype and options.
    ft = fittype( 'fourier5' );
    opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
    opts.Display = 'Off';
    opts.StartPoint = [0 0 0 0 0 0 0 0 0 0 0 0.362418764227411];
    
    % Fit model to data.
    [fitresult, gof] = fit( xData, yData, ft, opts );
    
    % Plot fit with data.
    figure( 'Name', 'untitled fit 1' );
    h = plot( fitresult, xData, yData );
    legend( h, 'Y1 vs. X1', 'untitled fit 1', 'Location', 'NorthEast' );
    % Label axes
    xlabel X1
    ylabel Y1
    grid on
    
    
