%open files
data=DataContainer;
data.parsefiles();

data.markErrorColumn('^data$', 'len$', 'lenErr');
data.markErrorColumn('^data$', 'angle$', 'angleErr');

% plotseries(data);
% plotseries(data, 'mixWithinDatum', false);
% plotseries(data, {'3', '2', '^data$'},...
%                  {"len$", 2, "angle$"},...
%                  {'angle$', 1, "len$"},...
%                  [1,2,2], 'gridSize',[1,2], 'iDataY', [1 2 2], 'mixWithinDatum', false);


plotseries(data, {'3', '2', '^data$'},...
                 {"len$", 2, "angle$"},...
                 {'angle$', 1, "len$"},...
                 [1,2,2], 'gridSize', [1,2]);